logs SOL price and RSI on console
JinxArcane235/jinx pull request #4
Opened 2024-11-26 06:53 UTC by shivaji43

1. **Set RSI and 4H candles** on your TradingView account manually.
2. **Install packages** by running `yarn` in your project folder.
3. **Navigate to `src` folder** and run `node index.js`.
4. **Login manually** with the same account and complete captcha.
5. **Price and RSI** will be logged every 30 minutes.
. 
 This pull request was created for https://app.gib.work/bounties/e6c5992c-08fd-43dc-8ce8-bc4398b09145 in an attempt to solve a bounty #1 . Payment for the bounty is immediately sent to the contributor after merge.

2024-11-26 06:55 UTC, shivaji43 commented
@JinxArcane235 please take a look and try it for yourself

2024-11-26 23:50 UTC, JinxArcane235 requested changes

2024-11-26 23:50 UTC, JinxArcane235 commented on src/index.js
> +const puppeteer = require('puppeteer');
Please convert this to TypeScript. Instead of using an IIAFE, create a main function and call it explicitly

2024-11-26 23:53 UTC, JinxArcane235 commented
after login nothing happens

<img width="857" alt="image" src="https://github.com/user-attachments/assets/5427facc-8c36-4a0b-ba5e-5bda15e8f1d4">

2024-11-27 01:33 UTC, shivaji43 commented
> after login nothing happens
> 
> <img alt="image" width="857" src="https://private-user-images.githubusercontent.com/189547207/390182060-5427facc-8c36-4a0b-ba5e-5bda15e8f1d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzEzMjUsIm5iZiI6MTczMjY3MTAyNSwicGF0aCI6Ii8xODk1NDcyMDcvMzkwMTgyMDYwLTU0MjdmYWNjLThjMzYtNGEwYi1iYTVlLTViZGExNWU4ZjFkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QwMTMwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjcxMzhjOGZlYzRiZmRkMGQ3NjQ0ZTViZDFhZTBjZjRmNTc2ZjFiZjFmNWUzOGE5NWMzNjE1MjNiMWZjZTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KAW235v61IVUvpUh5khB0lUA88nMfMQ4d7B-aEYlu-k">

I have put a 2 min time delay there for the login to be completed i will reduce it to 1 min.

2024-11-27 01:33 UTC, shivaji43 commented on src/index.js
> +const puppeteer = require('puppeteer');
> Please convert this to TypeScript. Instead of using an IIAFE, create a main function and call it explicitly

Okay no problem

2024-11-27 02:04 UTC, shivaji43 commented
![Screenshot 2024-11-27 073007](https://github.com/user-attachments/assets/ed38626f-2d3a-4a74-9486-8069679c1e88)

I have reduced the time for login to 1 minute and the info is logged every 1 second we can change it later on how we want it by just changing the milliseconds

now to run 
1)`yarn tsc`
2)`yarn dev`

2024-11-27 12:37 UTC, JinxArcane235 commented
Nice! Thanks

I just found two bugs, and I think we are done

This TradingView URL is different for me, which is: `https://www.tradingview.com/chart/hmLYX6Nq/?symbol=COINBASE%3ASOLUSD`

Also, the RSI query selector is returning a different value because the class name is the same

<img width="249" alt="image" src="https://github.com/user-attachments/assets/a0684e6b-edaf-40dd-8468-910a55861ee9">


![image](https://github.com/user-attachments/assets/51bbae53-fcc5-4cb0-a412-30bcd74b54a2)

2024-11-27 12:54 UTC, shivaji43 commented
![Screenshot 2024-11-27 182228](https://github.com/user-attachments/assets/0939937d-e38a-4953-85c2-cc3e0b9ebee0)

i cannot access this chart layout directly, is there any way you can tell how u setup this layout , and then i can change the css classname accordingly

2024-11-27 13:09 UTC, shivaji43 commented
![Screenshot 2024-11-27 183825](https://github.com/user-attachments/assets/3af242b5-7cd7-4383-881f-10a4e55c5e52)

you can Enable sharing here so i can see the chart layout

2024-11-27 13:20 UTC, JinxArcane235 commented
Enabled the sharing.

I checked here, and it seems that TradingView generates a unique url with an id for each user. I think the best approach here is to search for "SOL USD". What do you think?

2024-11-27 13:25 UTC, shivaji43 commented
> Enabled the sharing.
> 
> I checked here, and it seems that TradingView generates a unique url with an id for each user. I think the best approach here is to search for "USL USD". What do you think?

share me the link after enabling, i think that will work

2024-11-27 13:31 UTC, shivaji43 commented
Got it thank you I will fix the bugs right immediately @JinxArcane235

2024-11-27 13:32 UTC, JinxArcane235 commented
Thanks <3 @shivaji43

2024-11-27 13:49 UTC, shivaji43 commented
@JinxArcane235 you can check now , the correct rsi value is getting logged

2024-11-27 14:21 UTC, JinxArcane235 commented
Works!

2024-11-27 14:22 UTC, JinxArcane235 approved these changes

2024-11-27 14:25 UTC, shivaji43 commented
Thanks ♥️@JinxArcane235

2024-11-27 14:26 UTC, merged