Monitor and alert
JinxArcane235/jinx pull request #7
Opened 2024-11-26 09:30 UTC by Deadghoost

The script uses Winston for structured logging. Alerts and fetched data are logged to the console and stored in a file (tracker.log).
Streamlined Notifications:

Price and RSI alerts are logged if they exceed thresholds, but no external notifications are sent.
Tracking Logic:

Runs every 30 minutes using setInterval with an initial call to ensure immediate execution.. 
 This pull request was created for https://app.gib.work/bounties/e6c5992c-08fd-43dc-8ce8-bc4398b09145 in an attempt to solve a bounty #1 . Payment for the bounty is immediately sent to the contributor after merge.

2024-11-26 23:56 UTC, JinxArcane235 requested changes

2024-11-26 23:56 UTC, JinxArcane235 commented on priceTracker.ts
> +import puppeteer from 'puppeteer';
please put this file inside the `src` folder and add the script to start the project

2024-11-26 23:57 UTC, JinxArcane235 commented
its showing an error

<img width="1090" alt="image" src="https://github.com/user-attachments/assets/9e282d84-b213-4323-92b0-8fac77699fc0">

2024-11-27 09:47 UTC, Deadghoost commented on priceTracker.ts
> +import puppeteer from 'puppeteer';
i have updated the file and given it a new name which is now in the src folder

2024-11-27 14:41 UTC, closed without merging